name: Gated
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  gated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make check
